name: Build and test

on:
    push:

jobs:
    php-cs-fixer:
        name: PHP Coding Standards Fixer
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    tools: cs2pr

            -   name: Install PHP Coding Standards Fixer PHP dependencies
                run: composer install -d tools/php-cs-fixer --no-interaction --no-scripts --no-progress

            -   name: Run PHP Coding Standards Fixer
                run: ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php.dist --using-cache=no --allow-risky=yes --dry-run --diff --format=checkstyle | cs2pr

    test:
        name: Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.1', '8.2']
        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}

            -   name: Get composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install PHP dependencies
                run: composer install --no-interaction --no-scripts --no-progress

            -   name: Run test suite
                run: php vendor/bin/phpunit
